### ISSUE TITLE
7_android_php

### ISSUE THREAD

**Issue by Felipe-SG14** [Felipe-SG14/DevOps_Project#1]
# Conexión entre Android y PHP :rocket:

Código en Android para realizar la conexión con PHP

### DoD:
El programa es capaz de enviar diferente archivos JSON a un determinado archivo PHP y página web con opción de cambio. 

### Task List:
- [x] Definición de la función
- [x] Elección de parámetros
- [x] Desarrollo de la función
- [x] Manejo de verificaciones
- [x] Implementación de la función en la aplicación principal
- [x] Pruebas
- [x] Correcciones

### Responsables:
- @Felipe-SG14   :whale2:
- @juanmzmb     :frog:
